# Generated by Django 4.1.7 on 2023-04-07 14:43

import common.model_fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import logistics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0008_alter_companyactivitytype_advantages_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Помечен как удаленный"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=1024, verbose_name="Название"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1024,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "latitude",
                    common.model_fields.LatitudeField(
                        blank=True,
                        decimal_places=15,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    common.model_fields.LongitudeField(
                        blank=True,
                        decimal_places=15,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "contractor_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Транспортная компания"),
                            (2, "Экспедитор/диспетчер"),
                            (3, "Водитель"),
                        ],
                        verbose_name="Тип компании",
                    ),
                ),
                (
                    "transport_owns_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text='Указывается при типе контрагента "Транспортная компания" ',
                        null=True,
                        verbose_name="Количество собственных Т/С",
                    ),
                ),
                (
                    "avatar_or_company_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=logistics.models.contractor_storage,
                        verbose_name="Селфи для аватара/Логотип компании",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="company.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contractor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кем создан",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контрагент",
                "verbose_name_plural": "Контрагенты",
                "db_table": "contractor",
            },
        ),
        migrations.CreateModel(
            name="ContractorDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Помечен как удаленный"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "doc_type",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "Пакет учредительных документов")],
                        null=True,
                        verbose_name="Тип документа",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=logistics.models.contractor_storage,
                        verbose_name="Документ",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="logistics.contractor",
                        verbose_name="Контрагент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ контрагента",
                "verbose_name_plural": "Документы контрагента",
                "db_table": "contractor_documents",
            },
        ),
    ]
