# Generated by Django 4.1.7 on 2023-04-09 19:40

import common.model_fields
import common.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_alter_companyactivitytype_advantages_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logistics", "0002_alter_contractor_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransportApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Помечен как удаленный"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "shipping_address",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1024,
                        verbose_name="Адрес отгрузки",
                    ),
                ),
                (
                    "shipping_latitude",
                    common.model_fields.LatitudeField(
                        blank=True,
                        decimal_places=15,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="Широта адреса отгрузки",
                    ),
                ),
                (
                    "shipping_longitude",
                    common.model_fields.LongitudeField(
                        blank=True,
                        decimal_places=15,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="Долгота адреса отгрузки",
                    ),
                ),
                (
                    "delivery_address",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1024,
                        verbose_name="Адрес доставки",
                    ),
                ),
                (
                    "delivery_latitude",
                    common.model_fields.LatitudeField(
                        blank=True,
                        decimal_places=15,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="Широта адреса доставки",
                    ),
                ),
                (
                    "delivery_longitude",
                    common.model_fields.LongitudeField(
                        blank=True,
                        decimal_places=15,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="Долгота адреса доставки",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        max_length=64, verbose_name="Отправитель"
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        max_length=64, verbose_name="Отправитель"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Согласование условий"),
                            (2, "Машина загружена"),
                            (3, "Машина выгружена"),
                            (4, "Выполнена"),
                            (5, "Отменена"),
                        ],
                        default=1,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "amount",
                    common.model_fields.AmountField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Стоимость доставки",
                    ),
                ),
                (
                    "cargo_type",
                    models.CharField(
                        max_length=32, verbose_name="Характер груза"
                    ),
                ),
                (
                    "loading_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Зад"), (2, "Бок"), (3, "Верх")],
                        verbose_name="Формат погрузки",
                    ),
                ),
                ("weight", models.FloatField(verbose_name="Вес (кг.)")),
                (
                    "loading_hours",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=12,
                        verbose_name="Часы погрузки",
                    ),
                ),
                (
                    "weekend_work",
                    models.BooleanField(
                        default=False, verbose_name="Работа в выходные"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="", verbose_name="Комментарий"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=common.utils.get_current_user_id,
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кем создан",
                    ),
                ),
                (
                    "delivery_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_transport_app",
                        to="company.city",
                        verbose_name="Город доставки",
                    ),
                ),
                (
                    "shipping_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipping_transport_app",
                        to="company.city",
                        verbose_name="Город отгрузки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на транспорт",
                "verbose_name_plural": "Заявки на транспорт",
                "db_table": "transport_applications",
            },
        ),
    ]
