# Generated by Django 4.1.7 on 2023-04-21 12:47

import common.model_fields
import common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logistics", "0003_transportapplication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transportapplication",
            name="amount",
        ),
        migrations.AlterField(
            model_name="transportapplication",
            name="recipient",
            field=models.CharField(max_length=64, verbose_name="Получатель"),
        ),
        migrations.CreateModel(
            name="LogisticsOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Помечен как удаленный"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=1024, verbose_name="Название"
                    ),
                ),
                (
                    "amount",
                    common.model_fields.AmountField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Стоимость доставки",
                    ),
                ),
                (
                    "shipping_date",
                    models.DateTimeField(verbose_name="Дата отгрузки"),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "На рассмотрении"),
                            (2, "Одобрена"),
                            (3, "Отклонена"),
                        ],
                        default=1,
                        verbose_name="Статус предложения",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistics.transportapplication",
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistics.contractor",
                        verbose_name="Контрагент",
                    ),
                ),
                (
                    "logist",
                    models.ForeignKey(
                        default=common.utils.get_current_user_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение логиста",
                "verbose_name_plural": "Предложения логистов",
                "db_table": "logistic_offers",
            },
        ),
        migrations.AddField(
            model_name="transportapplication",
            name="approved_logistics_offer",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="logistics.logisticsoffer",
                verbose_name="Выбранное предложение логиста",
            ),
        ),
    ]
