# Generated by Django 4.1.7 on 2023-05-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0003_transportapplication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contractordocuments",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="contractordocuments",
            name="doc_type",
        ),
    ]
