# Generated by Django 4.1.7 on 2023-04-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0004_remove_transportapplication_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transportapplication",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Согласование условий"),
                    (2, "Машина загружена"),
                    (3, "Машина выгружена"),
                    (4, "Выполнена"),
                    (5, "Отменена"),
                    (6, "Машина в пути"),
                ],
                default=1,
                verbose_name="Статус",
            ),
        ),
    ]
