# Generated by Django 4.1.7 on 2023-05-13 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_message_options"),
        ("logistics", "0007_alter_transportapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="logisticsoffer",
            name="chat",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.chat",
                verbose_name="Чат",
            ),
        ),
        migrations.AlterField(
            model_name="logisticsoffer",
            name="shipping_date",
            field=models.DateTimeField(verbose_name="Дата загрузки"),
        ),
        migrations.AlterField(
            model_name="logisticsoffer",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "На рассмотрении"),
                    (2, "Одобрено"),
                    (3, "Отклонено"),
                ],
                default=1,
                verbose_name="Статус предложения",
            ),
        ),
        migrations.AlterField(
            model_name="transportapplication",
            name="approved_logistics_offer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="logistics.logisticsoffer",
                verbose_name="Выбранное предложение логиста",
            ),
        ),
        migrations.AlterField(
            model_name="transportapplication",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Назначение логиста"),
                    (2, "Машина загружена"),
                    (3, "Машина выгружена"),
                    (4, "Выполнена"),
                    (5, "Отменена"),
                ],
                default=1,
                verbose_name="Статус",
            ),
        ),
    ]
