# Generated by Django 4.1.7 on 2023-05-13 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("logistics", "0008_logisticsoffer_chat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transportapplication",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="transportapplication",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
