# Generated by Django 4.1.7 on 2023-05-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0004_remove_contractordocuments_comment_and_more"),
        ("logistics", "0010_alter_logisticsoffer_application"),
    ]

    operations = []
