# Generated by Django 4.1.7 on 2023-05-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0011_merge_20230519_1233"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContractorDocuments",
        ),
    ]
