# Generated by Django 4.1.7 on 2023-05-31 10:18

from django.db import migrations
from django.db.migrations import RunPython


def delete_duplicates(apps, schema_editor):
    TransportApplication = apps.get_model("logistics", "TransportApplication")
    objects = (
        TransportApplication.objects.all()
        .values_list("content_type", "object_id")
        .distinct()
    )
    for obj in objects:
        TransportApplication.objects.filter(
            pk__in=TransportApplication.objects.filter(
                content_type=obj[0], object_id=obj[1]
            ).values_list("pk", flat=True)[1:]
        ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0012_delete_contractordocuments"),
    ]

    operations = [RunPython(delete_duplicates)]
