# Generated by Django 4.1.7 on 2023-05-31 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("logistics", "0013_auto_20230531_1018"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="transportapplication",
            unique_together={("object_id", "content_type")},
        ),
    ]
