# Generated by Django 4.1.7 on 2023-08-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0017_transportapplication_receiver_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transportapplication",
            name="delivery_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата прибытия"
            ),
        ),
        migrations.AddField(
            model_name="transportapplication",
            name="loaded_weight",
            field=models.FloatField(
                blank=True,
                help_text="Поле для справки, не влияет на расчет стоимости",
                null=True,
                verbose_name="Загруженный вес",
            ),
        ),
        migrations.AddField(
            model_name="transportapplication",
            name="shipping_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата отгрузки"
            ),
        ),
    ]
