# Generated by Django 4.1.7 on 2023-08-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0018_transportapplication_delivery_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transportapplication",
            name="accepted_weight",
            field=models.FloatField(
                blank=True,
                help_text="Поле для справки, не влияет на расчет стоимости",
                null=True,
                verbose_name="Принятый вес",
            ),
        ),
    ]
