# Generated by Django 4.1.7 on 2023-05-09 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_equipmentcategory_equipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipments",
                to="product.equipmentcategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterModelTable(
            name="equipment",
            table="equipments",
        ),
    ]
