# Generated by Django 4.1.7 on 2023-10-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_recyclingcode_recyclables_recycling_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recyclables",
            name="recycling_code",
        ),
    ]
