# Generated by Django 4.1.7 on 2023-07-19 10:42

import common.model_fields
from django.db import migrations, models
import django.db.models.deletion
import finance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0010_recyclingcollectiontype_color"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoicePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Помечен как удаленный"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "amount",
                    common.model_fields.AmountField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Ожидает оплаты"),
                            (2, "Оплачен"),
                            (3, "Отменен"),
                            (4, "Возврат"),
                        ],
                        default=1,
                        verbose_name="Статус",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                        verbose_name="Компания",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата счета",
                "verbose_name_plural": "Оплаты счетов",
                "db_table": "invoice_payments",
            },
        ),
        migrations.CreateModel(
            name="PaymentOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Помечен как удаленный"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "За одну сделку"), (2, "За весь месяц")],
                        default=1,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        upload_to=finance.models.payment_doc_storage,
                        verbose_name="Документ",
                    ),
                ),
                (
                    "total",
                    common.model_fields.AmountField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "invoice_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.invoicepayment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платежное поручение",
                "verbose_name_plural": "Платежные поручения",
                "db_table": "payment_orders",
            },
        ),
    ]
