# Generated by Django 4.1.7 on 2023-07-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_invoicepayment_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentorder",
            name="name",
            field=models.CharField(
                db_index=True,
                default="None",
                max_length=1024,
                verbose_name="Название",
            ),
            preserve_default=False,
        ),
    ]
