# Generated by Django 4.1.7 on 2023-03-27 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={"verbose_name": "Чат", "verbose_name_plural": "Чаты"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "verbose_name": "Сообщение чата",
                "verbose_name_plural": "Сообщения чата",
            },
        ),
        migrations.RemoveField(
            model_name="chat",
            name="deal",
        ),
        migrations.AlterField(
            model_name="message",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chat",
            ),
        ),
    ]
