# Generated by Django 4.1.7 on 2023-04-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_chat_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="name",
            field=models.CharField(
                db_index=True,
                default="",
                max_length=1024,
                verbose_name="Название",
            ),
            preserve_default=False,
        ),
    ]
