# Generated by Django 4.1.7 on 2023-04-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chat_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Сообщение чата",
                "verbose_name_plural": "Сообщения чата",
            },
        ),
    ]
