# Generated by Django 4.1.3 on 2023-02-09 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_alter_companyactivitytype_advantages_and_more"),
        ("product", "0001_initial"),
        ("exchange", "0002_recyclablesapplication_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recyclablesapplication",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recyclables_applications",
                to="company.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AlterField(
            model_name="recyclablesapplication",
            name="recyclables",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="product.recyclables",
                verbose_name="Вторсырье",
            ),
        ),
    ]
