# Generated by Django 4.1.3 on 2023-03-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0003_alter_recyclablesapplication_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recyclablesapplication",
            name="images",
        ),
        migrations.AddIndex(
            model_name="imagemodel",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="images_content_d1d020_idx",
            ),
        ),
    ]
