# Generated by Django 4.1.3 on 2023-03-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0005_recyclablesdeal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recyclablesdeal",
            name="packing",
        ),
        migrations.AddField(
            model_name="recyclablesdeal",
            name="delivery_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата прибытия"
            ),
        ),
        migrations.AlterField(
            model_name="recyclablesdeal",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Согласование условий"),
                    (2, "Назначение логиста"),
                    (3, "Машина загружена"),
                    (4, "Машина выгружена"),
                    (5, "Окончательная приемка"),
                    (6, "Сделка закрыта"),
                    (7, "Проблемная сделка"),
                    (8, "Сделка отменена"),
                ],
                default=1,
                verbose_name="Статус",
            ),
        ),
    ]
