# Generated by Django 4.1.7 on 2023-03-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0006_remove_recyclablesdeal_packing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recyclablesapplication",
            name="moisture",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Влага или посторонние включения в %",
            ),
        ),
        migrations.AddField(
            model_name="recyclablesapplication",
            name="weediness",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Сорность в %"
            ),
        ),
    ]
