# Generated by Django 4.1.7 on 2023-03-30 17:10

from django.db import migrations, models
import django.db.models.deletion


def add_chat_to_deals(apps, schema_editor):
    RecyclablesDeal = apps.get_model("exchange", "RecyclablesDeal")
    Chat = apps.get_model("chat", "Chat")
    for recyclable_deal in RecyclablesDeal.objects.all():
        recyclable_deal.chat = Chat.objects.create()
        recyclable_deal.save()


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_chat_options_alter_message_options_and_more"),
        ("exchange", "0007_recyclablesapplication_moisture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recyclablesdeal",
            name="chat",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deal",
                to="chat.chat",
                verbose_name="Чат сделки",
            ),
        ),
        migrations.RunPython(add_chat_to_deals),
    ]
