# Generated by Django 4.1.7 on 2023-03-30 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_chat_options_alter_message_options_and_more"),
        ("exchange", "0008_recyclablesdeal_chat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recyclablesdeal",
            name="chat",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deal",
                to="chat.chat",
                verbose_name="Чат сделки",
            ),
        ),
    ]
