# Generated by Django 4.1.7 on 2023-04-09 20:24

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0009_alter_recyclablesdeal_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="recyclablesdeal",
            name="deal_number",
            field=models.CharField(
                default=common.utils.generate_random_sequence,
                max_length=10,
                verbose_name="Номер сделки",
            ),
        ),
    ]
