# Generated by Django 4.1.7 on 2023-04-24 17:36

from django.db import migrations, models
import django.db.models.deletion
import exchange.models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("exchange", "0010_recyclablesdeal_deal_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=512)),
                (
                    "document",
                    models.FileField(
                        upload_to=exchange.models.exchange_storage,
                        verbose_name="Документ",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Тип контента",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ сделки",
                "verbose_name_plural": "Документы сделки",
                "db_table": "documents",
            },
        ),
        migrations.AddIndex(
            model_name="documentmodel",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="documents_content_7d700d_idx",
            ),
        ),
    ]
