# Generated by Django 4.1.7 on 2023-04-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0011_documentmodel_and_more"),
        ("exchange", "0011_review"),
    ]

    operations = []
