# Generated by Django 4.1.7 on 2023-05-09 13:39

import common.model_fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_alter_companyactivitytype_advantages_and_more"),
        ("product", "0003_alter_equipment_category_alter_equipment_table"),
        ("exchange", "0012_merge_0011_documentmodel_and_more_0011_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Помечен как удаленный"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1024,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "latitude",
                    common.model_fields.LatitudeField(
                        blank=True,
                        decimal_places=15,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    common.model_fields.LongitudeField(
                        blank=True,
                        decimal_places=15,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "На проверке"),
                            (2, "Опубликована"),
                            (3, "Завершена"),
                            (4, "Отклонена"),
                        ],
                        default=1,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "deal_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Покупка"), (2, "Продажа")],
                        verbose_name="Тип сделки",
                    ),
                ),
                (
                    "with_nds",
                    models.BooleanField(default=False, verbose_name="С НДС"),
                ),
                (
                    "price",
                    common.model_fields.AmountField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(verbose_name="Количество"),
                ),
                (
                    "manufacture_date",
                    models.DateField(verbose_name="Дата производства"),
                ),
                (
                    "equipment_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Линия целиком"), (2, "Частями")],
                        default=1,
                        verbose_name="Тип оборудования",
                    ),
                ),
                (
                    "was_in_use",
                    models.BooleanField(default=False, verbose_name="Б/У"),
                ),
                (
                    "sale_by_parts",
                    models.BooleanField(
                        default=False, verbose_name="Продажа по частям"
                    ),
                ),
                (
                    "video_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="Ссылка на видео",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="", verbose_name="Комментарий"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="company.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_applications",
                        to="company.company",
                        verbose_name="Компания",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_applications",
                        to="product.equipment",
                        verbose_name="Оборудование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка по оборудованию",
                "verbose_name_plural": "Заявки по оборудованию",
                "db_table": "equipment_applications",
            },
        ),
    ]
