# Generated by Django 4.1.7 on 2023-05-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0013_equipmentapplication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipmentapplication",
            name="equipment_type",
        ),
    ]
