# Generated by Django 4.1.7 on 2023-05-22 05:25

import common.model_fields
import common.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_alter_companyactivitytype_advantages_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0004_alter_message_options"),
        ("exchange", "0014_remove_equipmentapplication_equipment_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Помечен как удаленный"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "shipping_address",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1024,
                        verbose_name="Адрес отгрузки",
                    ),
                ),
                (
                    "shipping_latitude",
                    common.model_fields.LatitudeField(
                        blank=True,
                        decimal_places=15,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="Широта адреса отгрузки",
                    ),
                ),
                (
                    "shipping_longitude",
                    common.model_fields.LongitudeField(
                        blank=True,
                        decimal_places=15,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="Долгота адреса отгрузки",
                    ),
                ),
                (
                    "delivery_address",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1024,
                        verbose_name="Адрес доставки",
                    ),
                ),
                (
                    "delivery_latitude",
                    common.model_fields.LatitudeField(
                        blank=True,
                        decimal_places=15,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="Широта адреса доставки",
                    ),
                ),
                (
                    "delivery_longitude",
                    common.model_fields.LongitudeField(
                        blank=True,
                        decimal_places=15,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="Долгота адреса доставки",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Согласование условий"),
                            (2, "Назначение логиста"),
                            (3, "Машина загружена"),
                            (4, "Машина выгружена"),
                            (5, "Окончательная приемка"),
                            (6, "Сделка закрыта"),
                            (7, "Проблемная сделка"),
                            (8, "Сделка отменена"),
                        ],
                        default=1,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "with_nds",
                    models.BooleanField(default=False, verbose_name="С НДС"),
                ),
                (
                    "price",
                    common.model_fields.AmountField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Цена за единицу",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(verbose_name="Количество"),
                ),
                (
                    "payment_term",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "По факту погрузки"),
                            (2, "По факту выгрузки"),
                            (3, "Другое"),
                        ],
                        default=1,
                        verbose_name="Условие оплаты",
                    ),
                ),
                (
                    "other_payment_term",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Иное условие оплаты",
                    ),
                ),
                (
                    "loaded_weight",
                    models.FloatField(
                        blank=True,
                        help_text="Поле для справки, не влияет на расчет стоимости",
                        null=True,
                        verbose_name="Загруженный вес",
                    ),
                ),
                (
                    "accepted_weight",
                    models.FloatField(
                        blank=True,
                        help_text="Поле для справки, не влияет на расчет стоимости",
                        null=True,
                        verbose_name="Принятый вес",
                    ),
                ),
                (
                    "shipping_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата отгрузки"
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата прибытия"
                    ),
                ),
                (
                    "who_delivers",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Поставщик"),
                            (2, "Покупатель"),
                            (3, "ВторПрайс"),
                        ],
                        default=3,
                        verbose_name="Кто доставляет",
                    ),
                ),
                (
                    "buyer_pays_shipping",
                    models.BooleanField(
                        default=True,
                        verbose_name="Доставку оплачивает покупатель",
                    ),
                ),
                (
                    "deal_number",
                    models.CharField(
                        default=common.utils.generate_random_sequence,
                        max_length=10,
                        verbose_name="Номер сделки",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="", verbose_name="Комментарий"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deals",
                        to="exchange.equipmentapplication",
                        verbose_name="Заявка",
                    ),
                ),
                (
                    "buyer_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_buy_deals",
                        to="company.company",
                        verbose_name="Покупатель",
                    ),
                ),
                (
                    "chat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_deal",
                        to="chat.chat",
                        verbose_name="Чат сделки",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=common.utils.get_current_user_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment_deals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь создавший сделку",
                    ),
                ),
                (
                    "delivery_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_equipment_deal",
                        to="company.city",
                        verbose_name="Город доставки",
                    ),
                ),
                (
                    "shipping_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipping_equipment_deal",
                        to="company.city",
                        verbose_name="Город отгрузки",
                    ),
                ),
                (
                    "supplier_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_sell_deals",
                        to="company.company",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сделка по оборудованию",
                "verbose_name_plural": "Сделки по оборудованию",
                "db_table": "equipment_deals",
            },
        ),
    ]
