# Generated by Django 4.1.7 on 2023-05-23 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0015_equipmentdeal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="name",
        ),
    ]
