# Generated by Django 4.1.7 on 2023-05-26 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0016_remove_review_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата добавления",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="is_deleted",
            field=models.BooleanField(
                default=False, verbose_name="Помечен как удаленный"
            ),
        ),
    ]
