# Generated by Django 4.1.7 on 2023-07-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0017_documentmodel_created_at_documentmodel_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentdeal",
            name="weight",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Вес в кг"
            ),
        ),
    ]
