# Generated by Django 4.1.7 on 2023-08-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0013_auto_20230803_1411"),
        ("exchange", "0018_equipmentdeal_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentmodel",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.company",
                verbose_name="Компания",
            ),
        ),
    ]
