# Generated by Django 4.1.7 on 2023-08-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0019_documentmodel_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentdeal",
            name="loading_hours",
            field=models.CharField(
                blank=True,
                default="",
                max_length=12,
                verbose_name="Часы погрузки",
            ),
        ),
        migrations.AddField(
            model_name="recyclablesdeal",
            name="loading_hours",
            field=models.CharField(
                blank=True,
                default="",
                max_length=12,
                verbose_name="Часы погрузки",
            ),
        ),
    ]
