# Generated by Django 4.1.7 on 2023-10-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0022_documentmodel_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="recyclablesapplication",
            name="total_weight",
            field=models.PositiveIntegerField(
                null=True, verbose_name="Полный вес заявки"
            ),
        ),
    ]
