# Generated by Django 4.1.7 on 2023-10-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0023_recyclablesapplication_total_weight"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recyclablesapplication",
            old_name="total_weight",
            new_name="full_weigth",
        ),
    ]
