# Generated by Django 4.1.3 on 2022-12-17 13:14

import common.model_fields
import company.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Помечен как удаленный"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=1024, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
                "db_table": "cities",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Помечен как удаленный"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=1024, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Описание"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=company.models.company_storage,
                        verbose_name="Фото/логотип",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        db_index=True,
                        max_length=12,
                        unique=True,
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Не проверенная"),
                            (2, "Проверенная"),
                            (3, "Надежная"),
                        ],
                        default=1,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        db_index=True,
                        max_length=128,
                        region=None,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1024,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "latitude",
                    common.model_fields.LatitudeField(
                        blank=True,
                        decimal_places=15,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    common.model_fields.LongitudeField(
                        blank=True,
                        decimal_places=15,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="Долгота",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компания",
                "verbose_name_plural": "Компании",
                "db_table": "companies",
            },
        ),
        migrations.CreateModel(
            name="CompanyAdditionalContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Помечен как удаленный"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "contact_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Телефон"),
                            (2, "Электронная почта"),
                            (3, "Whatsapp"),
                            (4, "Telegram"),
                        ],
                        verbose_name="Тип",
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=32, verbose_name="Контакт"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="", verbose_name="Комментарий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт компании",
                "verbose_name_plural": "Контакты компаний",
                "db_table": "company_contacts",
            },
        ),
        migrations.CreateModel(
            name="CompanyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Помечен как удаленный"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "doc_type",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "Устав"), (2, "Реквизиты"), (3, "ИНН")],
                        null=True,
                        verbose_name="Тип документа",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=company.models.company_storage,
                        verbose_name="Документ",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ компании",
                "verbose_name_plural": "Документы компаний",
                "db_table": "company_documents",
            },
        ),
        migrations.CreateModel(
            name="CompanyRecyclables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Помечен как удаленный"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "company_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Заготовитель"),
                            (2, "Переработчик"),
                            (3, "Продавец"),
                        ],
                        verbose_name="Тип компании",
                    ),
                ),
                (
                    "monthly_volume",
                    models.FloatField(
                        verbose_name="Примерный ежемесячный объем"
                    ),
                ),
                (
                    "price",
                    common.model_fields.AmountField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Цена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип вторсырья компании",
                "verbose_name_plural": "Типы вторсырья компаний",
                "db_table": "company_recyclables",
            },
        ),
        migrations.CreateModel(
            name="CompanyVerificationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Помечен как удаленный"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Новая"),
                            (2, "Проверена"),
                            (3, "Отклонена"),
                        ],
                        default=1,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="", verbose_name="Комментарий"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="company.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на верификацию",
                "verbose_name_plural": "Заявки на верификацию",
                "db_table": "company_verification_requests",
                "ordering": ["-created_at"],
                "get_latest_by": "-created_at",
            },
        ),
    ]
