# Generated by Django 4.1.3 on 2022-12-17 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="companyverificationrequest",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AddField(
            model_name="companyrecyclables",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recyclables",
                to="company.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AddField(
            model_name="companyrecyclables",
            name="recyclables",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="product.recyclables",
                verbose_name="Вторсырье",
            ),
        ),
        migrations.AddField(
            model_name="companydocument",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="company.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AddField(
            model_name="companyadditionalcontact",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="company.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="company.city",
                verbose_name="Город",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_staff": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="companies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="owner",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"role": 5},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="my_company",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="companyrecyclables",
            unique_together={("company_type", "recyclables")},
        ),
    ]
