# Generated by Django 4.1.3 on 2023-01-15 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
        ("company", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="companyrecyclables",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="companyrecyclables",
            name="action",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Покупаю"), (2, "Продаю")],
                default=1,
                verbose_name="Действие",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="companyrecyclables",
            unique_together={("action", "recyclables")},
        ),
        migrations.CreateModel(
            name="RecyclingCollectionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Помечен как удаленный"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=1024, verbose_name="Название"
                    ),
                ),
                (
                    "activity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Поставщик"),
                            (2, "Переработчик"),
                            (3, "Покупатель"),
                        ],
                        verbose_name="Вид деятельности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип сбора/переработки",
                "verbose_name_plural": "Типы сбора/переработки",
                "db_table": "recycling_collection_types",
                "unique_together": {("name", "activity")},
            },
        ),
        migrations.CreateModel(
            name="CompanyAdvantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Помечен как удаленный"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=1024, verbose_name="Название"
                    ),
                ),
                (
                    "activity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Поставщик"),
                            (2, "Переработчик"),
                            (3, "Покупатель"),
                        ],
                        verbose_name="Вид деятельности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преимущество компании",
                "verbose_name_plural": "Преимущества компании",
                "db_table": "company_advantages",
                "unique_together": {("name", "activity")},
            },
        ),
        migrations.RemoveField(
            model_name="companyrecyclables",
            name="company_type",
        ),
        migrations.CreateModel(
            name="CompanyActivityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Помечен как удаленный"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "activity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Поставщик"),
                            (2, "Переработчик"),
                            (3, "Покупатель"),
                        ],
                        verbose_name="Вид деятельности",
                    ),
                ),
                (
                    "advantages",
                    models.ManyToManyField(
                        to="company.companyadvantage",
                        verbose_name="Преимущества компании",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_types",
                        to="company.company",
                        verbose_name="Компания",
                    ),
                ),
                (
                    "rec_col_types",
                    models.ManyToManyField(
                        to="company.recyclingcollectiontype",
                        verbose_name="Тип сбора/переработки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Виды деятельности компании",
                "verbose_name_plural": "Виды деятельности компаний",
                "db_table": "company_activity_types",
                "unique_together": {("company", "activity")},
            },
        ),
    ]
