# Generated by Django 4.1.3 on 2023-01-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_companyrecyclables_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="companyrecyclables",
            unique_together=set(),
        ),
    ]
