# Generated by Django 4.1.3 on 2023-01-21 11:58

import common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0004_alter_companyrecyclables_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyverificationrequest",
            name="employee",
            field=models.ForeignKey(
                default=common.utils.get_current_user_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="companyverificationrequest",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Новая"),
                    (2, "Проверенная"),
                    (3, "Надежная"),
                    (4, "Отклонена"),
                ],
                default=1,
                verbose_name="Статус",
            ),
        ),
    ]
