# Generated by Django 4.1.3 on 2023-01-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_alter_companyverificationrequest_employee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="with_nds",
            field=models.BooleanField(default=False, verbose_name="С НДС"),
        ),
        migrations.AlterField(
            model_name="companyactivitytype",
            name="advantages",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="company.companyadvantage",
                verbose_name="Преимущества компании",
            ),
        ),
    ]
