# Generated by Django 4.1.3 on 2023-01-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_company_with_nds_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyactivitytype",
            name="rec_col_types",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="company.recyclingcollectiontype",
                verbose_name="Тип сбора/переработки",
            ),
        ),
    ]
