# Generated by Django 4.1.3 on 2023-01-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_alter_companyactivitytype_rec_col_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyactivitytype",
            name="advantages",
            field=models.ManyToManyField(
                blank=True,
                to="company.companyadvantage",
                verbose_name="Преимущества компании",
            ),
        ),
        migrations.AlterField(
            model_name="companyactivitytype",
            name="rec_col_types",
            field=models.ManyToManyField(
                blank=True,
                to="company.recyclingcollectiontype",
                verbose_name="Тип сбора/переработки",
            ),
        ),
    ]
