# Generated by Django 4.1.7 on 2023-06-28 11:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0009_region_city_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="recyclingcollectiontype",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FF0000",
                image_field=None,
                max_length=18,
                samples=None,
            ),
        ),
    ]
