# Generated by Django 4.1.7 on 2023-07-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0010_recyclingcollectiontype_color"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={
                "verbose_name": "Регион",
                "verbose_name_plural": "Регионы",
            },
        ),
    ]
