# Generated by Django 4.1.7 on 2023-08-03 13:06

import common.model_fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0011_alter_region_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="latitude",
            field=common.model_fields.LatitudeField(
                blank=True,
                decimal_places=15,
                max_digits=18,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="Широта",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="longitude",
            field=common.model_fields.LongitudeField(
                blank=True,
                decimal_places=15,
                max_digits=18,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="Долгота",
            ),
        ),
    ]
