# Generated by Django 4.1.7 on 2023-09-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0014_alter_companyactivitytype_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1024,
                null=True,
                verbose_name="Адрес",
            ),
        ),
    ]
