# Generated by Django 4.1.7 on 2023-10-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0015_alter_company_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="inn",
            field=models.CharField(
                db_index=True, max_length=32, unique=True, verbose_name="ИНН"
            ),
        ),
    ]
