# Generated by Django 4.1.7 on 2023-10-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0016_alter_company_inn"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="bank_name",
            field=models.CharField(
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Наименование банка",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="bic",
            field=models.CharField(
                max_length=15, null=True, unique=True, verbose_name="БИК"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="correction_account",
            field=models.CharField(
                max_length=32,
                null=True,
                unique=True,
                verbose_name="Коррекционный счет",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="head_full_name",
            field=models.CharField(
                max_length=100, null=True, verbose_name="ФИО директора"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="payment_account",
            field=models.CharField(
                max_length=32,
                null=True,
                unique=True,
                verbose_name="Расчетный счет",
            ),
        ),
    ]
