# Generated by Django 4.1.7 on 2023-10-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0017_company_bank_name_company_bic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="bank_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Наименование банка",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="bic",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="БИК"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="correction_account",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Корресп. счет",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="inn",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=32,
                unique=True,
                verbose_name="ИНН",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="payment_account",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                unique=True,
                verbose_name="Расчетный счет",
            ),
        ),
    ]
