# Generated by Django 4.1.3 on 2023-03-17 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_favorite"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="favorite",
            table="favorite",
        ),
    ]
