# Generated by Django 4.1.7 on 2023-10-16 16:55

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=user.models.user_storage,
                verbose_name="Фото/логотип",
            ),
        ),
    ]
