# Generated by Django 4.1.7 on 2023-07-11 12:08

from django.db import migrations, models
import django.db.models.deletion
import document_generator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedDocumentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Помечен как удаленный"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=512)),
                (
                    "document",
                    models.FileField(
                        upload_to=document_generator.models.generated_document_storage,
                        verbose_name="Документ",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Договор на отгрузку"),
                            (2, "Договор-заявка"),
                            (3, "Товарно-транспортная накладная"),
                            (4, "Счет-фактура"),
                            (5, "Договор приложение спецификация"),
                            (6, "Унифицированный транспортный документ"),
                            (7, "Акт"),
                        ],
                        verbose_name="Тип документа",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Тип контента",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сгенерированный документ",
                "verbose_name_plural": "Сгенерированные документы",
                "db_table": "generated_documents",
            },
        ),
        migrations.AddIndex(
            model_name="generateddocumentmodel",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="generated_d_content_1e0ea7_idx",
            ),
        ),
    ]
