# Generated by Django 4.1.7 on 2023-07-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_generator", "0002_alter_generateddocumentmodel_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generateddocumentmodel",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Договор на отгрузку"),
                    (2, "Договор-заявка"),
                    (3, "Товарно-транспортная накладная"),
                    (4, "Счет-фактура"),
                    (5, "Договор приложение спецификация"),
                    (6, "Унифицированный транспортный документ"),
                    (7, "Акт Покупателя"),
                    (8, "Акт Продавца"),
                    (9, "Акт за полный месяц"),
                ],
                verbose_name="Тип документа",
            ),
        ),
    ]
